name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v14  # Update to use Node.js 14

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          pip install black flake8
          python -m pip install --upgrade pip
          pip install praw vaderSentiment

      - name: Run linters
        run: |
          pylint reddit_post_analyser.py
          
      - name: Run lint action
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true

      - name: Check formatting
        run: black --check reddit_post_analyser.py
