name: Lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install praw vaderSentiment

    - name: Lint code
      run: |
        pylint reddit_post_analyser.py

    - name: Check formatting
      run: black --check reddit_post_analyser.py
