name: Lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies and set working directory
      run: |
        python -m pip install --upgrade pip
        pip install praw vaderSentiment pylint black
        cd $GITHUB_WORKSPACE

    - name: Lint code
      run: |
        pylint --init-hook="import sys, os; sys.path.append(os.path.dirname(os.path.realpath('.')))" reddit_post_analyser.py

    - name: Check formatting
      run: |
        black --check reddit_post_analyser.py
