name: Lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install praw vaderSentiment pylint black

    - name: Display Python and Pip versions
      run: |
        python --version
        pip --version

    - name: Set working directory and list files
      run: |
        cd $GITHUB_WORKSPACE
        ls -la

    - name: Copy .pylintrc if exists
      run: |
        cd $GITHUB_WORKSPACE
        if [ -f .pylintrc ]; then cp .pylintrc $GITHUB_WORKSPACE; fi

    - name: Lint code
      run: |
        pylint --rcfile .pylintrc reddit_post_analyser.py

    - name: Check formatting
      run: |
        black --check reddit_post_analyser.py
